### ISSUE TITLE
Syntax Highlight

### ISSUE THREAD

**Issue by sungbin5304** [Lzhiyong/TextEditor#1]
How can i set syntax highlight language?

**Comment by Lzhiyong** [comment]
> How can i set syntax highlight language?


private void init(Context context) {
        ......
        setLanguage(LuaLanguage.getInstance());
        ......
    }

call the setLanguage() method
for example java:
setLanguage(JavaLanguage.getInstance());

Currently, it is only a test app, and syntax highlighting may have bugs

**Comment by sungbin5304** [comment]
I checked that method(`setLanguage()`) and tried it before writing this issue, but I left this issue because of a bug in highlighting. **Thanks for the reply.**
